// Emit a PostgreSQL variant of prisma/schema.prisma (provider switch only) to
// prisma/postgres/schema.prisma, for static validation and baseline-migration
// generation. Usage: node scripts/pg-schema.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const src = readFileSync("prisma/schema.prisma", "utf8");
const pg = src.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');
if (pg === src) throw new Error("sqlite provider line not found");
mkdirSync("prisma/postgres", { recursive: true });
writeFileSync(
  "prisma/postgres/schema.prisma",
  "// GENERATED by scripts/pg-schema.mjs from prisma/schema.prisma — do not edit.\n" + pg
);
console.log("wrote prisma/postgres/schema.prisma");
